const GOOGLE_CLIENT_ID="808129330394-dagp56961vbank89vi7bc50pp4u7mgv8.apps.googleusercontent.com";
let token="",reviews=[],selected=null,maps=[],drawnLayers=[];
const $=id=>document.getElementById(id);
const apiUrl=path=>{if(/^https?:\/\//i.test(path))return path;const base=String(window.APP_CONFIG?.API_BASE_URL||"https://stepby-api-8-229-191-182.sslip.io").replace(/\/+$/,"");return path.startsWith("/api/")||path.startsWith("/auth/")?`${base}${path}`:path};
async function api(path,options={}){const timeoutMs=Number(options.timeoutMs)||30000,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const requestOptions={...options};delete requestOptions.timeoutMs;const res=await fetch(apiUrl(path),{...requestOptions,signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...requestOptions.headers}});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`HTTP ${res.status}`);return body}catch(error){if(error?.name==="AbortError")throw new Error("request_timeout");throw error}finally{clearTimeout(timer)}}
async function googleLogin(response){$("login-status").textContent="確認しています…";try{const res=await fetch(apiUrl("/auth/google"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id_token:response.credential})});const contentType=res.headers.get("content-type")||"";const body=contentType.includes("application/json")?await res.json():{};if(!res.ok)throw new Error(body.error||`認証サーバーへ接続できませんでした（${res.status}）`);if(!body.access_token)throw new Error("認証情報を取得できませんでした");token=body.access_token;$("login").hidden=true;$("app").hidden=false;await load()}catch(e){$("login-status").textContent=`ログインできません: ${e.message}`}}
function initGoogle(){if(!window.google)return setTimeout(initGoogle,100);google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:googleLogin});google.accounts.id.renderButton($("google-button"),{theme:"outline",size:"large"})}
function initMap(){if(maps.length)return;const aerial=L.map("map").setView([35.68,139.76],15),osm=L.map("osm-map").setView([35.68,139.76],15);L.tileLayer("https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg",{maxZoom:18,attribution:'<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank">国土地理院</a>'}).addTo(aerial);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(osm);maps=[aerial,osm];let syncing=false;maps.forEach((m,i)=>m.on("moveend zoomend",()=>{if(syncing)return;syncing=true;maps[1-i].setView(m.getCenter(),m.getZoom(),{animate:false});syncing=false}))}
async function load(){const p=new URLSearchParams({status:$("status").value,source:$("source").value,q:$("query").value,from:$("from").value,to:$("to").value});const body=await api(`/api/osm/reviews?${p}`);reviews=body.reviews||[];$("result-count").textContent=`${reviews.length}件`;$("list").innerHTML=reviews.length?reviews.map((r,i)=>`<button class="review" data-i="${i}"><b>${r.source_type==="legacy_record"?"既存":"新規"}</b> ${new Date(r.source_metadata?.startedAt||r.created_at).toLocaleString("ja-JP")}<br>${escapeHtml(r.username||"ユーザー不明")}<br><small>${r.review_status}${r.notification_status?` / 通知:${escapeHtml(r.notification_status)}`:""}</small></button>`).join(""):"<p>該当する記録はありません。</p>";document.querySelectorAll(".review").forEach(b=>b.onclick=()=>show(Number(b.dataset.i)))}
function escapeHtml(v){const d=document.createElement("div");d.textContent=String(v);return d.innerHTML}
function coordsFromOperations(ops){const out=[];(ops||[]).forEach(op=>{const x=op.after||op.before||{};(x.nodes||[]).forEach(n=>{if(Number.isFinite(+n.lat)&&Number.isFinite(+n.lon))out.push([+n.lat,+n.lon])})});return out}
function show(i){selected=reviews[i];document.querySelectorAll(".review").forEach((b,j)=>b.classList.toggle("active",i===j));initMap();drawnLayers.forEach(item=>item.map.removeLayer(item.layer));drawnLayers=[];let path=[];try{const g=JSON.parse(selected.path_geojson||"null");path=(g&&g.coordinates||[]).map(p=>[p[1],p[0]])}catch{}const raw=(selected.raw_points||[]).map(p=>[+p.lat,+p.lng]);const ops=coordsFromOperations(selected.elements),osmMap=maps[1];if(path.length)drawnLayers.push({map:osmMap,layer:L.polyline(path,{color:"#16a085",weight:6}).addTo(osmMap)});if(raw.length)drawnLayers.push({map:osmMap,layer:L.polyline(raw,{color:"#e74c3c",weight:3,dashArray:"5 6"}).addTo(osmMap)});if(ops.length)drawnLayers.push({map:osmMap,layer:L.polyline(ops,{color:"#ffd400",weight:4}).addTo(osmMap)});const all=[...path,...raw,...ops];if(all.length)maps.forEach(map=>map.fitBounds(all,{padding:[30,30]}));const legacy=selected.source_type==="legacy_record",classification=selected.source_metadata?.classification||"",recordedAt=escapeHtml(new Date(selected.source_metadata?.startedAt||selected.created_at).toLocaleString("ja-JP"));$("decision-bar").innerHTML=`<p><strong>${legacy?"既存記録":"新規記録"}</strong><br>${escapeHtml(selected.username||"不明")}・${recordedAt}</p><div class="primary-actions"><button class="approve" id="approve" ${!all.length?"disabled":""}>${legacy?"OSMへ公開する":"OSM公開を承認"}</button><button class="reject" id="reject">${legacy?"OSMへ公開しない":"却下"}</button></div>`;$("detail").innerHTML=`<h2>詳細・任意項目</h2><p>記録者: ${escapeHtml(selected.username||"不明")}<br>記録日時: ${recordedAt}<br>記録ID: ${escapeHtml(selected.record_id)}<br>状態: ${escapeHtml(selected.review_status)}${classification?`<br>自動分類: ${escapeHtml(classification)}`:""}<br>accuracy: ${legacy?"旧記録のため未保存":"GPS生座標を参照"}</p>${!all.length?'<p class="error">表示できる経路がありません。公開せず保留して調査してください。</p>':""}${selected.last_error?`<p class="error">直近の送信失敗: ${escapeHtml(selected.last_error)}</p>`:""}<details><summary>OSM変更予定</summary><pre>${escapeHtml(JSON.stringify(selected.elements,null,2))}</pre></details><label>管理者メモ（任意）<textarea id="note">${escapeHtml(selected.admin_note||"")}</textarea></label><label>却下理由（任意）<textarea id="reason">${escapeHtml(selected.rejection_reason||"")}</textarea></label><div class="secondary-actions"><button id="hold">保留</button><button id="save-note">メモ保存</button><button id="retry-email">通知再送</button></div>`;$("approve").onclick=()=>act("approve");$("reject").onclick=()=>act("reject");$("hold").onclick=()=>act("hold");$("save-note").onclick=()=>act("memo");$("retry-email").onclick=()=>act("retry-notification")}
function setBusy(busy){const overlay=$("loading-overlay");if(overlay)overlay.hidden=!busy;document.querySelectorAll("button,input,select,textarea").forEach(element=>{element.disabled=busy})}
function actionErrorMessage(code){if(code==="zero_length_tactile_segment"||code==="legacy_route_not_confirmed")return"現在のOSM道路上に、公開できる長さの経路を安全に確定できませんでした。この記録は保留して地図を確認してください。";if(code==="osm_version_conflict")return"公開直前にOSM側の道路が再度更新されました。変更は送信されていません。少し待ってから、もう一度お試しください。";if(code==="osm_data_temporarily_unavailable"||code==="osm_change_api_failed")return"最新のOSM道路情報を一時的に取得できませんでした。変更は送信されていません。少し待ってから、もう一度お試しください。";if(code==="request_timeout")return"処理の確認に時間がかかっています。画面操作を再開しました。一覧を更新して公開状態を確認してください。";return code}
async function act(action){if(!selected)return;const legacy=selected.source_type==="legacy_record",reason=$("reason").value.trim()||(legacy?"管理者判断によりOSMへ公開しない":""),note=$("note").value.trim();if(action==="reject"&&!reason)return alert("却下理由を入力してください。");if(action==="approve"&&!confirm("この記録をOSMへ公開しますか？"))return;setBusy(true);try{const body=await api(`/api/osm/reviews/${selected.review_id}/${action}`,{method:"POST",body:JSON.stringify({reason,note}),timeoutMs:75000});setBusy(false);alert(body.osmSent?"OSMへ公開しました。":body.alreadyPresent?"同じ点字ブロック情報がOSMに既にあることを確認しました。StepByの地図にも反映します。":action==="retry-notification"?"通知を再送しました。":action==="hold"?"保留しました。":action==="memo"?"メモを保存しました。":action==="approve"?"承認しました。安全条件を確認できなかったため、OSMには送信していません。":"公開しない記録として保存しました。");await load()}catch(e){setBusy(false);alert(`処理できません: ${actionErrorMessage(e.message)}`)}finally{setBusy(false)}}
$("reload").onclick=load;$("status").onchange=load;$("source").onchange=load;$("query").onkeydown=e=>{if(e.key==="Enter")load()};$("retry-notifications").onclick=async()=>{try{const r=await api("/api/osm/review-notifications/retry",{method:"POST",body:"{}"});alert(`${r.attempted}件を確認し、${r.sent}件送信しました。`);await load()}catch(e){alert(`通知を再試行できません: ${e.message}`)}};window.addEventListener("load",initGoogle);
