"""Regenerate js/icons.js from a Font Awesome Free subset.

Run from UI1/_new:  python tools/build-icons.py
Add a name to ICONS and re-run to pull in another glyph.
"""
import io
import json
import os
import re
import urllib.request

BASE = 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.1/svgs/'
UA = {'User-Agent': 'Mozilla/5.0'}

SOLID = """map-location-dot list-ul circle-plus bookmark user gear circle-question map arrow-left
shoe-prints location-crosshairs play stop pause camera trash-can pen xmark check triangle-exclamation
inbox chevron-right chevron-down chevron-up right-to-bracket right-from-bracket ranking-star language palette image plus
magnifying-glass circle-info road wheelchair elevator traffic-light volume-high person-walking
arrow-up-right-from-square globe sun moon text-height arrows-rotate location-dot layer-group clock
fire share-nodes stairs arrow-up-right-dots crosshairs braille ellipsis-vertical eye
circle-exclamation""".split()
BRANDS = ['google']

HEADER = r'''/* ===========================================================
   StepBy UI1 - Icon sprite  (generated by tools/build-icons.py - do not edit)

   Replaces the Font Awesome webfont CDN link: self-hosted, works offline, and
   every glyph is a real <svg> that inherits currentColor instead of a font
   character that flashes as a box while the webfont downloads.

   Icons: Font Awesome Free 6.5.1, CC BY 4.0 - https://fontawesome.com
   Usage: <span class="icon" data-icon="map"></span>   (hydrated on load)
          StepByIcons.svg('map')                       (for template strings)
   =========================================================== */
(function (w, d) {
  'use strict';

  var SPRITE = %(sprite)s;
  var NAMES = %(names)s;

  function injectSprite() {
    if (d.getElementById('stepby-icon-sprite')) return;
    var host = d.createElement('div');
    host.id = 'stepby-icon-sprite';
    host.setAttribute('aria-hidden', 'true');
    host.style.cssText = 'position:absolute;width:0;height:0;overflow:hidden';
    host.innerHTML = SPRITE;
    d.body.insertBefore(host, d.body.firstChild);
  }

  /** Inline <svg> markup for a sprite id. Decorative unless opts.label given. */
  function svg(name, opts) {
    var o = opts || {};
    var cls = 'icon' + (o.className ? ' ' + o.className : '');
    var label = o.label
      ? ' role="img" aria-label="' + String(o.label).replace(/"/g, '&quot;') + '"'
      : ' aria-hidden="true"';
    return '<svg class="' + cls + '"' + label + ' focusable="false"><use href="#i-' + name + '"></use></svg>';
  }

  /**
   * Turn <span class="icon" data-icon="map"> placeholders into real <svg>.
   *
   * The placeholder is REPLACED, not filled. Nesting an <svg class="icon">
   * inside a <span class="icon"> put the svg in an inline line-box, where
   * vertical-align dropped it a few pixels below the centre of its container
   * — enough for two icons in adjacent cards to look misaligned even though
   * their boxes were identical to the pixel.
   */
  function hydrate(root) {
    var nodes = (root || d).querySelectorAll('span[data-icon]');
    for (var i = 0; i < nodes.length; i++) {
      var el = nodes[i];
      var extra = (el.getAttribute('class') || '')
        .split(/\s+/).filter(function (c) { return c && c !== 'icon'; })
        .concat(el.getAttribute('data-icon-class') || []).join(' ');
      var tmp = d.createElement('div');
      tmp.innerHTML = svg(el.getAttribute('data-icon'), { className: extra });
      var node = tmp.firstChild;
      if (el.id) node.id = el.id;
      el.replaceWith(node);
    }
  }

  /**
   * Swap the glyph of an already-rendered icon, whichever form it is in.
   * hydrate() replaces placeholders, so a cached reference may be the <svg>
   * itself; writing innerHTML into that would nest one svg inside another.
   */
  function set(el, name) {
    if (!el) return el;
    if (el.tagName && el.tagName.toLowerCase() === 'svg') {
      el.querySelector('use').setAttribute('href', '#i-' + name);
      return el;
    }
    el.setAttribute('data-icon', name);
    hydrate(el.parentNode || d);
    return d.getElementById(el.id) || el;
  }

  function boot() {
    injectSprite();
    hydrate(d);
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot);
  else boot();

  w.StepByIcons = { svg: svg, set: set, hydrate: hydrate, injectSprite: injectSprite, names: NAMES };
})(window, document);
'''


def fetch(style, name):
    url = BASE + style + '/' + name + '.svg'
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode()


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    symbols, names, missing = [], [], []
    for style, group in (('solid', SOLID), ('brands', BRANDS)):
        for name in group:
            try:
                raw = fetch(style, name)
            except Exception:
                missing.append(name)
                continue
            viewbox = re.search(r'viewBox="([^"]+)"', raw).group(1)
            inner = re.sub(r'^.*?<svg[^>]*>|</svg>\s*$', '', raw, flags=re.S)
            inner = re.sub(r'<!--.*?-->', '', inner, flags=re.S).strip()
            symbols.append('<symbol id="i-%s" viewBox="%s">%s</symbol>' % (name, viewbox, inner))
            names.append(name)

    sprite = ('<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true">'
              + ''.join(symbols) + '</svg>')
    out = HEADER % {'sprite': json.dumps(sprite), 'names': json.dumps(sorted(names))}
    path = os.path.join(root, 'js', 'icons.js')
    io.open(path, 'w', encoding='utf-8', newline='\n').write(out)
    print('wrote %s (%d icons, %d bytes)' % (path, len(names), len(out)))
    if missing:
        print('MISSING:', ', '.join(missing))


if __name__ == '__main__':
    main()
